namespace QuickCheck;

/// <summary>
/// Represents one operation in a command sequence generated by
/// <see cref="Generate.CommandSequence{TModel, TSystem}"/>: whether it may follow the model
/// state it is generated in, how it changes that model, and how it runs against the real system.
/// </summary>
/// <typeparam name="TModel">The type of the model that stands in for the system during generation.</typeparam>
/// <typeparam name="TSystem">The type of the system under test.</typeparam>
/// <remarks>
/// <para>
/// A sequence is generated against the model alone, by calling <see cref="Precondition"/> and
/// <see cref="Update"/> on a fresh model from the sequence's initial-model factory, and run against
/// the system afterwards, by calling <see cref="Run"/> and then <see cref="Update"/> on another
/// fresh model. Each run of a sequence, including every replay while shrinking, starts from that
/// fresh model, so a command may hold only what is equal across replays: a value drawn from an
/// immutable model, or a key or id it looks up in the <c>model</c> argument of a mutable one. A
/// command that holds an object out of a mutable model holds the generation-time object, whose
/// state is not the state of the model passed to <see cref="Run"/>.
/// </para>
/// <para>
/// A record implementing this interface prints in a failure report with its members expanded, so
/// commands are best declared as records.
/// </para>
/// </remarks>
public interface ICommand<TModel, TSystem>
{
    /// <summary>
    /// Determines whether this command may be generated in the specified model state.
    /// </summary>
    /// <param name="model">The model state the command would follow.</param>
    /// <returns>
    /// <see langword="true"/> if the command may follow <paramref name="model"/>; otherwise,
    /// <see langword="false"/>. The default implementation returns <see langword="true"/>.
    /// </returns>
    /// <remarks>
    /// This method must not change <paramref name="model"/>. A command whose precondition is
    /// <see langword="false"/> is drawn again, up to ten times per step, before the example is
    /// discarded.
    /// </remarks>
    bool Precondition(TModel model) => true;

    /// <summary>
    /// Advances the model past this command.
    /// </summary>
    /// <param name="model">The model state before the command.</param>
    /// <returns>
    /// The model state after the command: <paramref name="model"/> itself when it was changed in
    /// place, or a new model when the model type is immutable.
    /// </returns>
    TModel Update(TModel model);

    /// <summary>
    /// Runs this command against the system under test and asserts what it observes.
    /// </summary>
    /// <param name="model">The model state before the command.</param>
    /// <param name="system">The system under test.</param>
    /// <remarks>
    /// Indicate failure by throwing, as a test assertion does. The model is the state before the
    /// command, so compare what the system returns with what <paramref name="model"/> held;
    /// <see cref="Update"/> is called after this method returns.
    /// </remarks>
    void Run(TModel model, TSystem system);
}
