<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <RootNamespace>QuickCheck.Xunit.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\QuickCheck.Xunit.v3\QuickCheck.Xunit.v3.csproj" />
    </ItemGroup>

</Project>
